version: '3'

services:
  app:
    image: node:carbon
    volumes:
      - .:/app
    working_dir: /app
    links:
      - db
    ports:
      - 80:80
      - 8080:8080
    command: /bin/sh -c "npm install && npm rebuild && npm run build && npm start"
 
  db:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - eun-mongo-data:/data/db
    command: /bin/sh -c "mongod --smallfiles"

volumes:
  eun-mongo-data:
